{
 "title": "Sesame - HTTPProxy",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Namespace", "query": "label_values(namespace)" },
   { "name": "VHost", "query": "label_values(vhost)" }
  ]
 },
 "panels": [
  {
   "title": "Total HTTProxies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(sesame_httpproxy{namespace=~\"$Namespace\"}) by (namespace)",
     "legendFormat": "Namespace: {{ namespace }}"
    }
   ]
  },
  {
   "title": "Orphaned HTTProxies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(sesame_httpproxy_orphaned{namespace=~\"$Namespace\"}) by (namespace)",
     "legendFormat": "Namespace: {{ namespace }}"
    }
   ]
  },
  {
   "title": "Valid HTTProxies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(sesame_httpproxy_valid{namespace=~\"$Namespace\",vhost=~\"$VHost\"}) by (namespace,vhost)",
     "legendFormat": "Namespace: {{ namespace }} ({{ vhost }})"
    }
   ]
  },
  {
   "title": "Invalid HTTProxies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(sesame_httpproxy_invalid{namespace=~\"$Namespace\",vhost=~\"$VHost\"}) by (namespace,vhost)",
     "legendFormat": "Namespace: {{ namespace }} ({{ vhost }})"
    }
   ]
  },
  {
   "title": "Root HTTProxies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(sesame_httpproxy_root{namespace=~\"$Namespace\"}) by (namespace)",
     "legendFormat": "Namespace: {{ namespace }}"
    }
   ]
  },
  {
   "title": "Sesame LDS Updates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_listener_manager_lds_update_failure",
     "legendFormat": "{{kubernetes_pod_name}} (failure)"
    },
    {
     "expr": "envoy_listener_manager_lds_update_success",
     "legendFormat": "{{kubernetes_pod_name}} (success)"
    },
    {
     "expr": "envoy_listener_manager_lds_update_rejected",
     "legendFormat": "{{kubernetes_pod_name}} (rejected)"
    }
   ]
  },
  {
   "title": "Sesame CDS Updates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_cluster_manager_cds_update_success",
     "legendFormat": "{{kubernetes_pod_name}} (Success)"
    },
    {
     "expr": "envoy_cluster_manager_cds_update_failure",
     "legendFormat": "{{kubernetes_pod_name}} (Failure)"
    },
    {
     "expr": "envoy_cluster_manager_cds_update_rejected",
     "legendFormat": "{{kubernetes_pod_name}} (Rejected)"
    }
   ]
  },
  {
   "title": "Sesame RDS Updates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_http_rds_update_success",
     "legendFormat": "{{kubernetes_pod_name}} (Success)"
    },
    {
     "expr": "envoy_http_rds_update_failure",
     "legendFormat": "{{kubernetes_pod_name}} (Failure)"
    },
    {
     "expr": "envoy_http_rds_update_rejected",
     "legendFormat": "{{kubernetes_pod_name}} (Rejected)"
    }
   ]
  }
 ]
}
{
 "title": "Envoy Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "query": "label_values(envoy_cluster_upstream_rq_time_bucket,namespace)"
   },
   {
    "name": "Service",
    "query": "label_values(envoy_cluster_upstream_rq_time_bucket,service)"
   },
   {
    "name": "Envoypod",
    "label": "Envoy Pod",
    "query": "label_values(envoy_server_memory_allocated,kubernetes_pod_name)"
   }
  ]
 },
 "panels": [
  { "title": "Envoy details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Envoy Open Connections",
   "type": "table",
   "description": "Shows the open connections to the http/https listeners.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(envoy_http_downstream_cx_active{envoy_http_conn_manager_prefix=\"ingress_http\"}) by (kubernetes_pod_name)"
    },
    {
     "expr": "sum(envoy_http_downstream_cx_active{envoy_http_conn_manager_prefix=\"ingress_https\"}) by (kubernetes_pod_name)"
    }
   ]
  },
  {
   "title": "Envoy heap memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "envoy_server_memory_heap_size{kubernetes_pod_name=~\"$Envoypod\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Envoy Allocated memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "envoy_server_memory_allocated{kubernetes_pod_name=~\"$Envoypod\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Active listeners",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_listener_manager_total_listeners_active{kubernetes_pod_name=~\"$Envoypod\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Warming Listeners",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_listener_manager_total_listeners_warming{kubernetes_pod_name=~\"$Envoypod\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Draining Listeners",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_listener_manager_total_listeners_draining{kubernetes_pod_name=~\"$Envoypod\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Downstream Total Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_http_downstream_cx_active{kubernetes_pod_name=~\"$Envoypod\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Downstream Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(envoy_http_downstream_rq_time_bucket{kubernetes_pod_name=~\"$Envoypod\"}[1m])) by (le, kubernetes_pod_name))",
     "legendFormat": "{{kubernetes_pod_name}} 90%"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(envoy_http_downstream_rq_time_bucket{kubernetes_pod_name=~\"$Envoypod\"}[1m])) by (le, kubernetes_pod_name))",
     "legendFormat": "{{kubernetes_pod_name}} 50% "
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_http_downstream_rq_time_bucket{kubernetes_pod_name=~\"$Envoypod\"}[1m])) by (le, kubernetes_pod_name))",
     "legendFormat": "{{kubernetes_pod_name}} 99%"
    }
   ]
  },
  {
   "title": "Downstream RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_total{kubernetes_pod_name=~\"$Envoypod\"}[1m])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Downstream CPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_cx_total{kubernetes_pod_name=~\"$Envoypod\"}[1m])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Service details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Endpoint Percentage Health",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(envoy_cluster_membership_healthy{namespace=~\"$Namespace\",service=~\"$Service\"}) by (namespace, service) / avg(envoy_cluster_membership_total{namespace=~\"$Namespace\",service=~\"$Service\"}) by (namespace, service)",
     "legendFormat": "{{namespace}}/{{service}}"
    }
   ]
  },
  {
   "title": "Healthy Endpoints",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(envoy_cluster_membership_healthy{namespace=~\"$Namespace\",service=~\"$Service\"}) by (namespace, service)",
     "legendFormat": "{{namespace}}/{{service}}"
    }
   ]
  },
  {
   "title": "Unhealthy Endpoints",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(envoy_cluster_membership_total{namespace=~\"$Namespace\",service=~\"$Service\"}) by (namespace, service) - avg(envoy_cluster_membership_healthy{namespace=~\"$Namespace\",service=~\"$Service\"}) by (namespace, service)",
     "legendFormat": "{{namespace}}/{{service}}"
    }
   ]
  },
  {
   "title": "Total Endpoints",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(envoy_cluster_membership_total{namespace=~\"$Namespace\",service=~\"$Service\"}) by (namespace, service)",
     "legendFormat": "{{namespace}}/{{service}}"
    }
   ]
  },
  {
   "title": "Upstream 2xx Responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{namespace=~\"$Namespace\",service=~\"$Service\",envoy_response_code_class=~\"2\"}[1m])) by (namespace,service)",
     "legendFormat": "{{namespace}}/{{service}}"
    }
   ]
  },
  {
   "title": "Upstream 3xx Responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{namespace=~\"$Namespace\",service=~\"$Service\",envoy_response_code_class=\"3\"}[1m])) by (namespace,service)",
     "legendFormat": "{{namespace}}/{{service}}"
    }
   ]
  },
  {
   "title": "Upstream 4xx Responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{namespace=~\"$Namespace\",service=~\"$Service\",envoy_response_code_class=\"4\"}[1m])) by (namespace,service)",
     "legendFormat": "{{namespace}}/{{service}}"
    }
   ]
  },
  {
   "title": "Upstream 5xx Responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{namespace=~\"$Namespace\",service=~\"$Service\",envoy_response_code_class=\"5\"}[1m])) by (namespace,service)",
     "legendFormat": "{{namespace}}/{{service}}"
    }
   ]
  },
  {
   "title": "Upstream Total Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_active{namespace=~\"$Namespace\",service=~\"$Service\"}) by (namespace, service)",
     "legendFormat": "{{namespace}}/{{service}}"
    }
   ]
  },
  {
   "title": "Upstream Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 42 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_cluster_upstream_rq_time_bucket{service=~\"$Service\",namespace=~\"$Namespace\"}[1m])) by (le, service, namespace))",
     "legendFormat": "{{namespace}}/{{service}} 99%"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(envoy_cluster_upstream_rq_time_bucket{service=~\"$Service\",namespace=~\"$Namespace\"}[1m])) by (le, service, namespace))",
     "legendFormat": "{{namespace}}/{{service}} 90%"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(envoy_cluster_upstream_rq_time_bucket{service=~\"$Service\",namespace=~\"$Namespace\"}[1m])) by (le, service, namespace))",
     "legendFormat": "{{namespace}}/{{service}} 50% "
    }
   ]
  },
  {
   "title": "Upstream CPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_total{namespace=~\"$Namespace\",service=~\"$Service\"}[1m])) by (namespace, service)",
     "legendFormat": "{{namespace}}/{{service}}"
    }
   ]
  },
  {
   "title": "Upstream RPS",
   "type": "graph",
   "description": "Displays the number of Requests per Second being performed against each Upstream.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_total{namespace=~\"$Namespace\",service=~\"$Service\"}[1m])) by (service,namespace)",
     "legendFormat": "{{namespace}}/{{service}}"
    }
   ]
  }
 ]
}
{
 "title": "Sesame APIserver stats",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Operation",
    "query": "label_values(sesame_eventhandler_operation_total, op)"
   },
   {
    "name": "Kind",
    "query": "label_values(sesame_eventhandler_operation_total, kind)"
   }
  ]
 },
 "panels": [
  {
   "title": "Observed API server operations by kind and operation",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(sesame_eventhandler_operation_total{kind=~\"$Kind\", op=~\"$Operation\"}[1m])) by (op,kind)",
     "legendFormat": "{{kind}} {{op}}"
    }
   ]
  },
  {
   "title": "Observed API server operations total by kind",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(sesame_eventhandler_operation_total{kind=~\"$Kind\"}[1m])) by (kind)",
     "legendFormat": "{{kind}} operations"
    }
   ]
  }
 ]
}