# httpproxy-unique-fqdn instantiates an HTTPProxyUniqueFQDN
# ConstraintTemplate.
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: HTTPProxyUniqueFQDN
metadata:
  name: httpproxy-unique-fqdn
  labels:
    app: sesame
spec:
  match:
    kinds:
      - apiGroups: ["projectsesame.io"]
        kinds: ["HTTPProxy"]
