apiVersion: projectsesame.io/v1
kind: HTTPProxy
metadata:
  name: root
  namespace: projectsesame-roots
spec:
  virtualhost:
    fqdn: local.projectsesame.io
  routes:
  - services:
    - name: rootapp
      port: 80
  - services:
    - name: secureapp
      port: 80
    conditions:
      - prefix: /secure
