apiVersion: projectsesame.io/v1
kind: HTTPProxy
metadata:
  name: blogsite
  namespace: projectsesame-marketing
spec:
  includes:
    - name: infosite
      conditions:
      - prefix: /info
  routes:
    - services:
        - name: wwwblog
          port: 80
---
apiVersion: projectsesame.io/v1
kind: HTTPProxy
metadata:
  name: infosite
  namespace: projectsesame-marketing
spec:
  routes:
    - services:
        - name: info
          port: 80
