apiVersion: v1
kind: ConfigMap
metadata:
  name: sesame
  namespace: projectsesame
data:
  Sesame.yaml: |
    rateLimitService:
      extensionService: projectsesame/ratelimit
      domain: Sesame
      failOpen: false
