---
apiVersion: v1
kind: Namespace
metadata:
  name: projectsesame
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sesame
  namespace: projectsesame
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: envoy
  namespace: projectsesame
