---
apiVersion: v1
kind: Service
metadata:
  name: sesame
  namespace: projectsesame
spec:
  ports:
  - port: 8001
    name: xds
    protocol: TCP
    targetPort: 8001
  selector:
    app: sesame
  type: ClusterIP
