---
apiVersion: v1
kind: Namespace
metadata:
  name: projectsesame-auth
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: projectsesame-auth-htpasswd
  namespace: projectsesame-auth
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: projectsesame:authserver:htpasswd
  namespace: projectsesame-auth
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: projectsesame:authserver:htpasswd
  namespace: projectsesame-auth
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: projectsesame:authserver:htpasswd
subjects:
  - kind: ServiceAccount
    name: projectsesame-auth-htpasswd
    namespace: projectsesame-auth
