---
apiVersion: projectsesame.io/v1
kind: HTTPProxy
metadata:
  name: echo
  namespace: projectsesame-auth
spec:
  virtualhost:
    fqdn: local.projectsesame.io
    tls:
      secretName: envoycert
  routes:
    - services:
        - name: ingress-conformance-echo
          port: 80
